version: '3.9'

services:
  mongodb:
    image: mongo:6
    container_name: mongo_container
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongo_data:
